--- 

name: Docker Build action test locally !!!

on:
  workflow_dispatch:

jobs:
  Docker-Actions-in-Building:
     runs-on: ubuntu-latest
     environment:
      name: Checkout repo
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Test Local Action
       id: test-action
       uses: ./
       with:
        milliseconds: 1000
       
     - name: Print Output
       id: output
       run: echo "${{ steps.test-action.outputs.time }}"  