--- 

name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  checkoutRepo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

  buildDockerImage:
    runs-on: ubuntu-latest
    needs: [checkoutRepo]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t ghcr.io/guithi0777/github-actions-metadata-g/actions/large_alligator:v3 .

  dockerLogin:
    runs-on: ubuntu-latest
    needs: [checkoutRepo,buildDockerImage]
    steps:
    - name: Docker login
      run: docker login ghcr.io -u dockergt15100 -p ${{ secrets.GITHUB_TOKEN }}

  Testlocalaction:
    runs-on: ubuntu-latest
    needs: [checkoutRepo,buildDockerImage,dockerLogin,]
    steps:
    - name: Test Local Action
      id: test-action
      uses: actions/large_alligator@v3
      with:
        milliseconds: 1000
  Sortie:
    runs-on: ubuntu-latest
    needs: [checkoutRepo,buildDockerImage,dockerLogin,Testlocalaction]
    steps:
    - name: Print Output
      id: output
      run: echo "${{ steps.test-action.outputs.time }}"           

  Dockerpushaction:
    runs-on: ubuntu-latest
    needs: [checkoutRepo,buildDockerImage,dockerLogin,Testlocalaction,Sortie]
    steps:
    - name: Push Docker image
      run: docker push ghcr.io/guithi0777/github-actions-metadata-g/actions/large_alligator:v3 .

  
  
